language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: So/48YH6H9+WA4/ChUep57O9b5jh/aMMXEICKmjdIrAeNAxOv9WZLWmRZ4bH4joSEDgInk1BxL0sLa/lIZMSIqy+n+G23mTdrB0zpkatMmhBwH9rqjpeLzrPTJJ8kc1FFu53yAvhoIAAhXWDZexkbMc9PqOLUCvULOhGCIYqju/604FLl1Eer8SKKVDbM1FWH1WcAsQuHdIrPHsy1gSLg0Uh9Va9pKWOkx9KFePLsUzCEzdsunL9eq1ebH/bPLqNRYEKCYahMn38E16bZhaXVGzqDREmbZzaZwHAsFcPLPnn+3ZEtGlF0LG+ZH+xOe3xtF/3eCSag1fOtVi3dY+5O//OH6Fbv8iut0zWywplQP00B5I975ekMe6g+Rr8bVo3vUx+4mjgFZfB7n3iOFeiJrkEUB7qk2q1z0NyOHUVu3m+lM3qsAQIeYd81I9QaN6+HEl47JmhxWsehmX6JI9DT1GozPEtIOL1dFdzphjHrs7wH+ePNLPOLx0/WWDTvuNQvj/DmclCFDQeY4jE9eN+3ZFlVHgrHOUOvaWdH/UMTg9r6wK7mTx2Rr70rYL9M9ZnO4w+Ck8QGQeP6cMZ/kfiMtZ9zazAN2RndJocRZN7acE7G5w8RTbeLcIq00KZiyaMSh7zmtGlqHhJIvMHLggD4pLiKFilSOgUDBzQSceudtE=
  file:
    - "rehype-sanitize.js"
    - "rehype-sanitize.min.js"
  on:
    tags: true
